[build]
  publish = "src/"

# [[plugins]]
#   # Installs the Lighthouse Build Plugin for all deploy contexts
#   package = "@netlify/plugin-lighthouse"

# [[headers]]
#   TODO: change fonts to far future expiry and manage cache busting manually
