[build]
  base = '.'
  command = 'npm run start'
  publish = "src/dist"

# Turn off asset processing to support preloading fonts with a link tag. Netlify
# doesn't rewrite link tags to match their hashed asset name, or allow
# fine-grained exclusion of fonts from processing.
# https://answers.netlify.com/t/asset-optimization-preloading-fonts/3197/10
[build.processing]
  skip_processing = true

# Set selected assets to far future expiry to eek out a tiny bit more
# performance, at the cost of managing cache busting manually via file names.
# This is a minor optimization, but I can't bring myself to make network
# roundtrips on every page load for long-lived assets.
[[headers]]
  for = "/*.woff2"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    s-maxage=31536000,
    immutable'''

[[headers]]
  for = "/favicon-64.png"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    s-maxage=31536000,
    immutable'''

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9

  [plugins.inputs]
    output_path = "reports/lighthouse.html"
